name: ussd_vip
description: A new Flutter application.

publish_to: '1.0.1'
version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cached_network_image: ^2.3.3
  intl: ^0.17.0-nullsafety.2
  url_launcher:
  page_view_indicator: ^2.0.4
  carousel_slider: ^3.0.0
  path_provider: ^1.3.0
  flutter_statusbarcolor: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 800
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500